baseurl = "/"
languageCode = "en-us"
languageLang = "en"
title = "The Shaky Experience"

# RSS, categories and tags disabled for an easy start
# See configuration options for more details: 
# https://gohugo.io/getting-started/configuration/#toml-configuration
disableKinds = ["RSS", "taxonomy", "taxonomyTerm"]

[menu]
    [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 100

    [[menu.main]]
    identifier = "podcast"
    name = "Podcast"
    url = "/podcast"
    weight = 101
    
    [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 102

    [[menu.main]]
    identifier = "contact"
    name = "Contact/Booking"
    url = "/contact"
    weight = 103

    [[menu.main]]
    identifier = "bio"
    name = "Bio"
    url = "/bio"
    weight = 104